import { SiteConfig } from "@/types";

export const siteConfig: SiteConfig = {
  name: "MyBlog",
  description: "Generated by create next app",
  url: "https://example.com",
  ogImage: "",
  links: {
    x: "https://example.com",
    github: "",
  },
}
